services:
  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    ports:
      - "80:4173"  # Map HTTP port for local development
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    ports:
      - "8000:8000"
    restart: always