FROM node:18-alpine3.17 as build

WORKDIR /code
COPY ./src/frontend /code

RUN npm install
RUN npm run build

FROM nginx:1.21-alpine

COPY --from=build /code/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]