services:
  frontend:
    image: public.ecr.aws/s0o1g6r1/frontend
    ports:
      - "80:4173"
    depends_on:
      - backend
    restart: always

  backend:
    image: public.ecr.aws/s0o1g6r1/backend
    ports:
      - "8000:8000"
    restart: always